alias lsa='ls -FA'
alias lsl='ls -FAlh'
alias gadd='git add -A && git status'
alias g='git status'
alias gd='git diff'
alias gstat='git status'
alias gcom='git commit'
alias glog='git log --pretty=oneline'
alias gch='git checkout'
alias gf='git flow'
alias grecent="git for-each-ref --sort='authordate:iso8601' --format=' %(authordate:relative)%09%(refname:short)' refs/heads"
